#!/bin/bash
# 
# export XDG_CURRENT_DESKTOP=bspwm
# export GDK_BACKEND=x11
# export XDG_SESSION_TYPE=x11

# Настройки X11
xset s 300
xset dpms 600

# Запуск фоновых служб
sxhkd &
xss-lock -- betterlockscreen -l --show-layout &

# --- Настройки bspwm ---
bspc config border_width         1
bspc config window_gap          6
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#fd2e59"
bspc config split_ratio          0.5
bspc config focus_follows_pointer true
bspc config pointer_modifier	super
bspc config single_monocle	     true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
bspc config top_padding 0



bspc config external_rules_command ~/.config/bspwm/external_rules.sh 


mapfile -t MONITORS < <(xrandr --query | awk '/ connected/ && !/disconnected/ {print $1}')

PRIMARY=$(xrandr --query | awk '/ primary/ {print $1; exit}')

NUM_MONITORS=${#MONITORS[@]}

if [ "$NUM_MONITORS" -eq 1 ]; then
    bspc monitor "${MONITORS[0]}" -d 1 2 3 4 5

elif [ "$NUM_MONITORS" -eq 2 ]; then
    if [ -n "$PRIMARY" ]; then
        SECONDARY=""
        for mon in "${MONITORS[@]}"; do
            if [ "$mon" != "$PRIMARY" ]; then
                SECONDARY="$mon"
                break
            fi
        done
    else
        PRIMARY="${MONITORS[0]}"
        SECONDARY="${MONITORS[1]}"
    fi

    bspc monitor "$PRIMARY"   -d 1 2 3 4 5
    bspc monitor "$SECONDARY" -d 6 7 

else
    DESKTOP_NAMES=(1 2 3 4 5 6 7 8 9 0)
    IDX=0
    for MON in "${MONITORS[@]}"; do
        NAMES=()
        for i in {0..2}; do
            if [ $((IDX + i)) -lt ${#DESKTOP_NAMES[@]} ]; then
                NAMES+=("${DESKTOP_NAMES[$((IDX + i))]}")
            fi
        done
        if [ ${#NAMES[@]} -gt 0 ]; then
            bspc monitor "$MON" -d "${NAMES[@]}"
        fi
        IDX=$((IDX + 3))
    done
fi


pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x dunst > /dev/null || dunst &
pgrep -x nm-applet > /dev/null || nm-applet --indicator &
pgrep -x volumeicon > /dev/null || volumeicon &
pgrep -x flameshot > /dev/null || flameshot &
pkill battery-alert; ~/bin/battery-alert &
if ! pgrep -x polkit-gnome-authentication-agent-1 > /dev/null; then
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
autorandr -c &
xsetroot -cursor_name left_ptr &

feh --bg-scale ~/Pictures/wallpaper.jpg &

~/.config/polybar/launch.sh &

pkill battery-alert; ~/bin/battery-alert &
