#!/bin/sh

# Настройки X11
xset s 300
xset dpms 600

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Запуск демонов и утилит (в фоне)
xsettingsd &    
sxhkd &
xss-lock -- betterlockscreen -l --show-layout &
autorandr -c &

# Запуск основной сессии через dbus-launch
exec dbus-launch --exit-with-session bspwm
