exec sxhkd &
exec bspwm

# Настройки энергосбережения и блокировки
xset s 300          # Экран "засыпает" через 5 минут (активирует screensaver)
xset dpms 600       # DPMS: выключить дисплей через 10 минут

# Запуск xss-lock (реагирует на xset s)
pgrep -x xss-lock > /dev/null || xss-lock -l -- betterlockscreen -l &

exec dbus-launch --exit-with-session bspwm